title: WIND RIVER Avalanche Validator
email: info@rockinghat.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
domain: "windriver.rockinghat.com"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://windriver.rockinghat.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: RockingHatLLC
github_username:  rockinghat
# Build settings
theme: minima
plugins:
  - jekyll-feed
destination: docs
# lsi: false
# safe: true
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge   
